// <auto-generated />
namespace Railway.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Releasev10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Releasev10));
        
        string IMigrationMetadata.Id
        {
            get { return "201809160940345_Release-v.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
